security:
    providers:
        a0:
            id:
                a0_user_provider

    firewalls:
        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator

    # Protect all API routes except api/recipes/all 
    access_control:
        - { path: ^/api/recipes/all, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/recipes/*, roles: ROLE_OAUTH_AUTHENTICATED }
